USE macrohistory_rolap
GO

create or alter view [PENN_USD_TEMPORARY_TABLE]
AS
SELECT * FROM PENN_USD_Calculated_fn('GDP-TOTAL-LCU-CURRENT',N'GDP-TOTAL-USD-CURRENT')
GO


EXEC PENN_USD_Injector
GO

create or alter view [PENN_USD_TEMPORARY_TABLE]
AS
SELECT * FROM PENN_USD_Calculated_fn('GDP-GFCF-LCU-CURRENT',N'GDP-GFCF-USD-CURRENT')
GO


EXEC PENN_USD_Injector

GO
