-- This script generates a list of all views and prints them.
-- The Print @SQL command (commented out) then generates a list of them
-- the Exec (@SQL) command actually deletes them
-- the list currently generated by the ROLAP package is listed in comments
-- to avoid implementing it accidentally


DECLARE @sql VARCHAR(MAX) = ''
        , @crlf VARCHAR(2) = CHAR(13) + CHAR(10) ;

SELECT @sql = @sql + 'DROP VIEW ' + QUOTENAME(SCHEMA_NAME(schema_id)) + '.' + QUOTENAME(v.name) +';' + @crlf
FROM   sys.views v

-- PRINT @sql;
-- EXEC(@sql);

/*

DROP VIEW [dbo].[PENN_USD_TEMPORARY_TABLE];
DROP VIEW [dbo].[IFSSeasonalAdjustmentRemoval];
DROP VIEW [dbo].[PENN_USD_Calculated_KeyFinder];
DROP VIEW [dbo].[IFSSeasonalAdjustmentRemoval_KeyFinder];
DROP VIEW [dbo].[UN_RU_Corrector];
DROP VIEW [dbo].[UN_RU_Corrector_KeyFinder];
DROP VIEW [dbo].[MADDISON_RU_Corrector];
DROP VIEW [dbo].[MADDISON_RU_Corrector_KeyFinder];
DROP VIEW [dbo].[WID_RU_Corrector];
DROP VIEW [dbo].[WID_RU_Corrector_KeyFinder];
DROP VIEW [dbo].[PENN_ExchangeRates];
DROP VIEW [dbo].[WID_NDP_USD_Calculated];
DROP VIEW [dbo].[WID_USD_Calculated_KeyFinder];
DROP VIEW [dbo].[WID_National_Income];
DROP VIEW [dbo].[WID_National_Income_Calculated];
DROP VIEW [dbo].[WID_National_Income_Calculated_KeyFinder];
DROP VIEW [dbo].[WID_National_Income_USD_Calculated];
DROP VIEW [dbo].[WID_National_Income_USD_Calculated_KeyFinder];
DROP VIEW [dbo].[WID_Foreign_Income_USD_Calculated];
DROP VIEW [dbo].[WID_Foreign_Income_USD_Calculated_KeyFinder];
DROP VIEW [dbo].[Macrohist_Indexed_rgdppc];
DROP VIEW [dbo].[Barro_Ursua_Indexed_gdp];
DROP VIEW [dbo].[Maddison_Population];
DROP VIEW [dbo].[WDI2018_2005_REALGDP_BASE];
DROP VIEW [dbo].[WDI2018_2006_REALGDP_BASE];
DROP VIEW [dbo].[Macrohist_WDI2018_Deindexed];
DROP VIEW [dbo].[BARRO_URSUA_WDI2018_Deindexed];
DROP VIEW [dbo].[Macrohist_cleaner];
DROP VIEW [dbo].[Barro_Ursua_cleaner];
DROP VIEW [dbo].[AddedDefinitions];
DROP VIEW [dbo].[NormalisedAddedDefinitions];
*/